### ISSUE TITLE
Test 2 : Posting a post results in a redirect to /post/zyz and rendering of post content and edit link

### ISSUE THREAD

**Issue by Sudhathankavel** [Sudhathankavel/djangoprojects#12]
-verify redirect
-verify content is in html
-Fetch post from DB
-verify edit link is correct

**Comment by aitchnyu** [comment]
You should verify fetching with correct and wrong edit link.

**Comment by Sudhathankavel** [comment]
verify content is in html - is it to verify the page content or the link content?
